/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'blicon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'bli-tablet': '&#xe942;',
		'bli-timer': '&#xe941;',
		'bli-router': '&#xe93d;',
		'bli-hotel': '&#xe93e;',
		'bli-idea': '&#xe93f;',
		'bli-phone-ring': '&#xe940;',
		'bli-bell': '&#xe939;',
		'bli-keylock': '&#xe93a;',
		'bli-badge': '&#xe93b;',
		'bli-pricetag': '&#xe93c;',
		'bli-gym': '&#xe937;',
		'bli-pool': '&#xe938;',
		'bli-credit-card': '&#xe934;',
		'bli-package': '&#xe935;',
		'bli-ticket': '&#xe936;',
		'bli-sort': '&#xe92f;',
		'bli-near-location': '&#xe930;',
		'bli-filter-icon': '&#xe931;',
		'bli-bed': '&#xe932;',
		'bli-globe': '&#xe933;',
		'bli-cc-icon': '&#xe919;',
		'bli-mark': '&#xe91a;',
		'bli-two-people': '&#xe91b;',
		'bli-triangle-down': '&#xe91c;',
		'bli-tail-arrow-right': '&#xe91f;',
		'bli-breakfast': '&#xe920;',
		'bli-calendar': '&#xe921;',
		'bli-cicilan': '&#xe922;',
		'bli-confirm-failed': '&#xe923;',
		'bli-internet-banking': '&#xe924;',
		'bli-map-icon': '&#xe925;',
		'bli-marker': '&#xe926;',
		'bli-car-icon': '&#xe927;',
		'bli-marker-outline': '&#xe928;',
		'bli-prod-list': '&#xe929;',
		'bli-promo-tag': '&#xe92a;',
		'bli-search-thin': '&#xe92b;',
		'bli-star-fill': '&#xe92c;',
		'bli-e-money': '&#xe92d;',
		'bli-wifi': '&#xe92e;',
		'bli-gift': '&#xe918;',
		'bli-android': '&#xe915;',
		'bli-apple': '&#xe916;',
		'bli-windows': '&#xe917;',
		'bli-time-passage': '&#xe912;',
		'bli-locked': '&#xe90f;',
		'bli-eye-close': '&#xe910;',
		'bli-eye-open': '&#xe911;',
		'bli-speech-bubble': '&#xe90e;',
		'bli-spinner-arrow': '&#xe901;',
		'bli-arrow-right': '&#xe902;',
		'bli-arrow-down': '&#xe903;',
		'bli-arrow-left': '&#xe904;',
		'bli-arrow-up': '&#xe905;',
		'bli-check-list': '&#xe906;',
		'bli-trash': '&#xe907;',
		'bli-dot3': '&#xe908;',
		'bli-smile2': '&#xe909;',
		'bli-smile5': '&#xe90a;',
		'bli-smile4': '&#xe90b;',
		'bli-smile1': '&#xe90c;',
		'bli-smile3': '&#xe90d;',
		'bli-facebook': '&#x58;',
		'bli-google-plus': '&#x59;',
		'bli-heart-fill': '&#x60;',
		'bli-instagram': '&#x61;',
		'bli-heart-outline': '&#x62;',
		'bli-twitter': '&#x63;',
		'bli-youtube': '&#x64;',
		'bli-cat-gi': '&#x65;',
		'bli-cat-hol': '&#x54;',
		'bli-cat-mvg': '&#x55;',
		'bli-cat-ora': '&#x56;',
		'bli-cat-tkt': '&#xe900;',
		'bli-cat-fpr': '&#x21;',
		'bli-cat-fwn': '&#x22;',
		'bli-cat-hobby': '&#x23;',
		'bli-cat-hpt': '&#x24;',
		'bli-cat-ian': '&#x25;',
		'bli-cat-kam': '&#x26;',
		'bli-cat-kke': '&#x27;',
		'bli-cat-kul': '&#x28;',
		'bli-cat-kom': '&#x29;',
		'bli-cat-oto': '&#x2a;',
		'bli-cat-ele': '&#x2b;',
		'bli-subkategori-o': '&#x2c;',
		'bli-top-circle': '&#x2d;',
		'bli-balloon': '&#x2e;',
		'bli-bag': '&#x2f;',
		'bli-cc-call': '&#x30;',
		'bli-cc-email': '&#x31;',
		'bli-close': '&#x32;',
		'bli-list': '&#x33;',
		'bli-grid': '&#x34;',
		'bli-delete': '&#x35;',
		'bli-done': '&#x36;',
		'bli-done-o': '&#x37;',
		'bli-down-arrow': '&#x38;',
		'bli-up-arrow': '&#x39;',
		'bli-left-arrow': '&#x3a;',
		'bli-right-arrow': '&#x3b;',
		'bli-edit-pencil': '&#x3c;',
		'bli-filter': '&#x3e;',
		'bli-home': '&#x3f;',
		'bli-menu-hamburger': '&#x40;',
		'bli-more-white': '&#x41;',
		'bli-settings': '&#x42;',
		'bli-circle-empty': '&#x43;',
		'bli-circle-selected': '&#x44;',
		'bli-reload': '&#x45;',
		'bli-search': '&#x46;',
		'bli-share': '&#x47;',
		'bli-warning': '&#x48;',
		'bli-view-module': '&#x49;',
		'bli-video': '&#x4a;',
		'bli-usp-quality': '&#xe913;',
		'bli-usp-payment': '&#xe914;',
		'bli-usp-shipping': '&#xe91d;',
		'bli-usp-installment': '&#xe91e;',
		'bli-usp-cc': '&#x4d;',
		'bli-user': '&#x4e;',
		'bli-subcategory': '&#x4f;',
		'bli-star-half': '&#x50;',
		'bli-star': '&#x51;',
		'bli-small-search': '&#x52;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/bli-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
